### ISSUE TITLE
openGD77CPS and OpenDM-1801 it's not possible to connect

### ISSUE THREAD

**Issue by mti-sk** [rogerclarkmelbourne/OpenGD77CPS#14]
Using openGD77CPS, I was able to upload new firmware to the Baofeng DM-860.
The OpenGD77 driver was installed automatically with the software and recognized by the operating system.
when I try to download data from the radio, I always get the same message: device not found

OS: Win10 64bit 1809
Firmware version: OpenDM1801 build Jun 27 2020
Software version: OpenGD77CPS 2020.07.01

**Comment by rogerclarkmelbourne** [comment]
See this thread.

**Comment by mti-sk** [comment]
Hi, 

I really don't know what you mean.
I went through the OpenGD77 forum and links on the Internet, but nothing
about communication between OpenGD77 CPS and openDM1801. 

Best regards 

Dňa 12.07.2020 01:48 Roger Clark napísal(a):

> See this thread. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/rogerclarkmelbourne/OpenGD77CPS/issues/14#issuecomment-657148824
[2]
