### ISSUE TITLE
openGD77CPS and Win10 (Czech version)

### ISSUE THREAD

**Issue by mti-sk** [rogerclarkmelbourne/OpenGD77CPS#15]
Hi,
sorry I wrote a new issue again, but my previous one was closed.
After reading the thread for discussion, I found out that the communication problem is mainly only with WIN10 (Czech version):
http://opengd77.com/viewtopic.php?f=12&t=92&sid=34c3e597f7c336c86dd108b9a8c7dd65

On my win10CZ I tried to list all COM ports in powershell using a regular expression.
For an unknown reason (probably a human error) there is still a gap behind the port designation in this version !!!
regexp for com port can be something like this ".? \ ((COM \ d +) \) [ ]?$"  or  ".? \ ((COM \ d +) \) [ ]{0,1}$"

my output:
1.used a space before the end of the line
PS C: \ Users \ xxx> (Get-WmiObject -query "SELECT * FROM Win32_PnPEntity" | Where {$ _. Name -Match ".? \ ((COM \ d +) \) $"}). Name
Dell Wireless 5809e Gobi (TM) 4G LTE Mobile Broadband NMEA Port (COM4)
Dell Wireless 5809e Gobi (TM) 4G LTE Mobile Broadband DM Port (COM5)

2. without space before the end of line:
PS C: \ Users \ xxx> (Get-WmiObject -query "SELECT * FROM Win32_PnPEntity" | Where {$ _. Name -Match ".? \ ((COM \ d +) \) $"}). Name
PS C: \ Users \ xxx> <nothing output>

Could this information be useful?

**Comment by HegrJan** [comment]
I have the same problem on Czech Win7, the port name ends with a space. I think the \(COM\d+\) is quite sufficient anchor, so I'd just drop the $ at the end of the regex.
@rogerclarkmelbourne , should I apply a pull request for such a subtle change?

**Comment by rogerclarkmelbourne** [comment]
Yes.

If you can try changing the regex and see if it fixes the problem.

We've been unable to replicate the problem, even by changing the language on Windows to Czech, because it looks like there is some underlying differences when some languages are selected during the Windows installation process.
