### ISSUE TITLE
Frequency values in VFO-1 and VFO-2 are not saved

### ISSUE THREAD

**Issue by timurmelnikov** [rogerclarkmelbourne/OpenGD77CPS#21]
Frequency values in VFO-1 and VFO-2 are not saved.
Whatever I enter, the frequency is displayed as 564.00000.
Screenshot - https://prnt.sc/tyf97v

**Comment by rogerclarkmelbourne** [comment]
564Mhz is beyond the hardware range of the radio, however I will check if there is another bug with the VFO

**Comment by cx8abf** [comment]
The pages VFO A and VFO B, also dont permit to add a tone for repeater.

**Comment by rogerclarkmelbourne** [comment]
@cx8abf 
Rx and Tx tones can be set for the VFO

**Comment by rogerclarkmelbourne** [comment]
@timurmelnikov and @cx8abf  I think I found what is causing this, but I'm not entirely sure why.

I will do a new release of the CPS probably at the weekend which has a fix.

**Comment by rogerclarkmelbourne** [comment]
This should be fixed now (last week actually)
