### ISSUE TITLE
Setting the master power level

### ISSUE THREAD

**Issue by cjeffcoat2** [rogerclarkmelbourne/OpenGD77CPS#28]
After loading the latest software, channels now have a field to edit power level, most of my channels are set for master, a few of them I have set reduced power, but I do not see a place to set the master level four all channels set to master.￼￼

**Comment by rogerclarkmelbourne** [comment]
The CPS does not have control of any of the options or master settings in the radio

Its impractical for the CPS to be able to do this, because the internal data structure for the settings changes frequently, and it would be unmanageable for me to have a system where the CPS could control the settings regardless of firmware version.

i.e CPS and firmware version are independent.

**Comment by cjeffcoat2** [comment]
OK, perhaps this is not the place to post this question but how do you set the master power level then? All of my channels have reverted to 50 mW.

**Comment by rogerclarkmelbourne** [comment]
What on the GD77S ?

I just tested and mine is OK working OK.

Which radio type ?

**Comment by rogerclarkmelbourne** [comment]
When did you last download the firmware.  There was a fix 15 mins ago (roughly)

**Comment by cjeffcoat2** [comment]
I downloaded it about five minutes ago. I will try again later this evening.

**Comment by cjeffcoat2** [comment]
I’m so sorry, I neglected to put that information in there. It’s the regular GD 77.

**Comment by rogerclarkmelbourne** [comment]
There was a bug in the version I posted 12 hours ago.

It should be fixed now

**Comment by cjeffcoat2** [comment]
Hi,

 

I just downloaded the latest unstable firmware and loaded it.  Channels that are set to “master” are appearing in the radio to be 50 MW.

**Comment by cjeffcoat2** [comment]
Hey, please close this issue, I figured it out, I was expecting a master power level to be in the software or somewhere in the radio, I changed one of my channels power levels that was set for master to a level that I would like for the master level to be set up and all other channels followed suit that were set for the master level. Channels that were set specifically for anything other than the master level retained their settings. This can be closed.￼

**Comment by rogerclarkmelbourne** [comment]
Master power level is the default for the VFO and all the channels , unless you set a pre-channel power setting, which is an override

I had to do this for backwards compatibility, as a lot of people still want the radio to operate exactly the same was as it did before this new feature.

I know its initially a bit confusing, but it kinda makes sense after a while.

i.e if a channel uses the Master power, then it also controls the Master power.

If the channel uses its own specific power level, then changing the power on that channel, only changes its individual power setting.

Note. Changing a channels individual power setting does not immediately permanently save to the codeplug, and is just a temporary override on the individual power.

If you have an individual power setting on a channel, then change it from e.g. using SK2 + Left or Right and want to make that change permanent, you need to go into the Channel Details screen and force it to save permanently 

The shortcut for this is SK2 + Green , SK2 + Green,  or hold SK2 down and press Green twice.

There are technical reasons why the power does not get saved immediately permanently as well as usability reasons. Channel data is stored in Flash memory, which takes a relatively long time to write to, as a whole 4k of flash (a page), needs to first be read from the Flash via a slow data bus, then the page needs to be erased, and then the modified 4k page with the change to the power needs to be written back to Flash.

This can take several hundred milliseconds and completely ties up the CPU preventing DMR reception.

Also the Flash memory has a limited number of erase cycles and gets slower and slower with the more erase cycles that its put through.
