### ISSUE TITLE
Exception at .csv Import of Channels

### ISSUE THREAD

**Issue by dc7jzb** [rogerclarkmelbourne/OpenGD77CPS#35]
At the release from the 20th October the Import of Channel csv files ends with an exception Failure.

Its the same on "Import Update/Append" and "Import Clear All"
On a earlier version it works fine.

![OpenGD77cps_exeption](https://user-images.githubusercontent.com/2844409/97117403-dc1a8b80-1703-11eb-9ee6-2eda4ec41401.png)

**Comment by dc7jzb** [comment]
I tried it with different files wich I had exported in a earlier Version, and for test I exported a file with the CPS from 20th October.
The Software can not import it.

**Comment by rogerclarkmelbourne** [comment]
OK.

Possibly some change to the limitation of the Contact when TG list is selected have caused this problem.

I will investigate

**Comment by rogerclarkmelbourne** [comment]
Yes. It is that.

I now have a fix.

I'll update it later

**Comment by rogerclarkmelbourne** [comment]
Fixed now.

https://github.com/rogerclarkmelbourne/OpenGD77CPS/releases/tag/R2020.10.26
