### ISSUE TITLE
The radio settings after firmware update

### ISSUE THREAD

**Issue by SQ9DKV** [rogerclarkmelbourne/OpenGD77CPS#42]
It would be good if the firmware update did not reset the radio settings to default

**Comment by rogerclarkmelbourne** [comment]
The settings are **only** reset when the structure of the data in the settings changes.

It doesn't happen with every firmware update, only for updates which add functionality which needs the settings structure to be modified in any way, including the addition of new settings to configure the new feature.

There is no other solution except to reset the settings if the structure changes
