### ISSUE TITLE
5++ power inficator 

### ISSUE THREAD

**Issue by SQ9DKV** [rogerclarkmelbourne/OpenGD77CPS#43]
In the lastest beta firmware D2020.11.12.01 from 2020-11-12 01:07:23Z, the 5++ power indicator is displayed as -W+.  Is it a bug or a proper one? If appropriate, why such a change. 5 ++ is more intuitive

**Comment by rogerclarkmelbourne** [comment]
Please read the release notes for the beta firmware.
