### ISSUE TITLE
Settings  reset to default

### ISSUE THREAD

**Issue by SQ9DKV** [rogerclarkmelbourne/OpenGD77CPS#44]
Settings  reset to default by pressing SK2+PowerOn could ask uuser for confirmation

**Comment by rogerclarkmelbourne** [comment]
This is not the repo for the firmware, its the repo for the CPS. 

See

https://github.com/rogerclarkmelbourne/OpenGD77

And No. 

We don't make the change you suggest because SK2 + Power on is executed before the firmware is running and the display is functioning at this time.
