### ISSUE TITLE
Battery level

### ISSUE THREAD

**Issue by VA3NDP** [rogerclarkmelbourne/OpenGD77CPS#45]
Fully charged battery on RD-5R reading 94% on full and climbs to 96% after it is out of the charger and turned on for a few min. Is this just a calibration concern? It's not really a big deal, I just wanted to let you know. Cheers 
VA3NDP

**Comment by f1rmb** [comment]
Hi,

   I suggest you to search the forum about this topic, e.g.:
https://opengd77.com/viewtopic.php?f=7&t=1390&p=12337&hilit=fully+charge#p12333
https://opengd77.com/viewtopic.php?f=11&t=528&p=5298&hilit=fully+charge#p4354

And again, wrong repo ;-)

Cheers.
...
Daniel

**Comment by VA3NDP** [comment]
Shoot. Yup. I have already read that section as well. Apparently I should have finished my coffee first this morning.
