### ISSUE TITLE
Squelch Open timing

### ISSUE THREAD

**Issue by VA3NDP** [rogerclarkmelbourne/OpenGD77CPS#46]
Most channels on DMR with correct TS & CC entered and while in SCAN mode. The Radio will stop and indicate signal but it sometimes won't open squelch at all or it takes 10-20 seconds to open and often misses entire key-up. Happens even with full signal. Have second radio next to it that opens right away. Sometimes you can even hear the "hiss" sound but no voice. Almost sounds like it's looking for something. I notice this on SCAN only. It seems to be much better when it's just sitting on a channel or In VFO mode. TS,CC filter set to "OFF" and DMR filter set to "None".

**Comment by f1rmb** [comment]
Hi,

  Don't set CC to OFF, it's not designed to work like this.
When setting CC to OFF, it's like scanning the all CC, and it's long. It's designed to find the Color Code value when it's unknown.

Cheers.
...
Daniel

**Comment by VA3NDP** [comment]
Sorry. I said "OFf" and meant "ON". Apologies. I do realize the SCAN of CC's ans TS's take extra time. I just had the wrong setting in my head. I should have verified it first. Sorry. ![image](https://user-images.githubusercontent.com/74636021/100745667-9fe6e480-33ad-11eb-98b9-80c5b95f6944.jpeg)

**Comment by VA3NDP** [comment]
Shoot. Wrong Repo. Sorry. Am I able to move it. I tried to delete with no luck

**Comment by VA3NDP** [comment]
Sorry Roger!! Still trying to get used to the GITHUB.

**Comment by f1rmb** [comment]
:-)
