### ISSUE TITLE
OpenGD77CPS R2020.12.24.01 shows wrong version number...

### ISSUE THREAD

**Issue by dl9sec** [rogerclarkmelbourne/OpenGD77CPS#51]
OpenGD77CPS R2020.12.24.01 shows R2020.12.13.01 as version...

73, Thorsten

**Comment by rogerclarkmelbourne** [comment]
Oops

I forgot to update text :-(

I'll correct it and replace the existing file

**Comment by rogerclarkmelbourne** [comment]
Should be fixed now
