### ISSUE TITLE
Locking up when programming firmware

### ISSUE THREAD

**Issue by g7jiq** [rogerclarkmelbourne/OpenGD77CPS#54]
I have noticed that the last 3 ver of software lock up when flashing firmware,
It appears to program fine but never shows a complette box with the ok button, and you have to terminate the program.
The last ver that works ok is R2020.12.29.01

**Comment by rogerclarkmelbourne** [comment]
Which radio type.?

Considering that there have been nearly 300 downloads of this for the GD77 and nearly 100 for the DM1801 and RD-5R, I don't think there is anything fundamentally wrong with the firmware or the loader.

**Comment by rogerclarkmelbourne** [comment]
OK

I'll check if there is a bug.

Note. These latest releases are marked as Beta and not release versions.

**Comment by rogerclarkmelbourne** [comment]
Umm.

Looks like the upload completes but it hangs because it can't find a message.

I'll investigate

**Comment by g7jiq** [comment]
I am well aware that they are beta ver, 
But I was just informing you that there was a slight problem,
All is working ok now.

**Comment by rogerclarkmelbourne** [comment]
Thanks.

The problem seemed to be a typo / paste'o
