### ISSUE TITLE
Minimize and maximize buttons are missing from the windows caption bars

### ISSUE THREAD

**Issue by PedroPauloBrazil** [rogerclarkmelbourne/OpenGD77CPS#55]
Hi! In the most recent versions (> 2020.10.26) of OpenGD77CPS, the minimize and maximize windows buttons disappeared from the caption bars, so we can no longer expand or reduce them. This makes the operation of the program somewhat uncomfortable, especially on denser screens, with a lot of data, since the fixed window sizes do not allow us to use the available space on the screen as it used to.
Could you please check?
Thank You and Happy New Year de Paulo, PU2OIP

**Comment by f1rmb** [comment]
Hi,

   Do you mean from the panels (like Channel, VFO, etc) ?.
In this case, that's normal, as none of the panels are resizable (the window content won't shrink / expand, no sliders will appear, etc). So, those containers have to be fixed sized, by design (old behavior was simply wrong, and ugly).

Cheers.

**Comment by PedroPauloBrazil** [comment]
Hello, Daniel

I agree that some smaller panels can be fixed, but the more complex others like contacts, channels, etc. need to be resizeable, in my opinion, to let the things more visible. That's why I like the approach adopted by the older versions: not so beautiful, but more useful.

Regards,

Paulo

Em 4 de janeiro de 2021 14:09:11 BRT, Daniel Caujolle-Bert <notifications@github.com> escreveu:

**Comment by rogerclarkmelbourne** [comment]
The Channels screen does resize the list of channels, so I can see for that screen allowing resizing (not maximising and minimising), would be beneficial

The Contacts screen does not resize the list. The list is slightly larger than the current size of the screen, but allowing the screen to maximise would not, without other changes, allow any more contacts to be viewed.

**Comment by PedroPauloBrazil** [comment]
Ok, thanks for your time, Daniel and Roger.
Just giving my 2 cents about usability, don't worry.

Regards, and keep the good job!

Paulo

**Comment by rogerclarkmelbourne** [comment]
I think for the Channels and Contacts screen, I will enable resizing, but not the Maximise / Minimise boxes.

I won't be enabling the resizing etc on any other screens, as they do not benefit from being made larger, and are not usable if made smaller
