### ISSUE TITLE
Broadcasting in digital mode with shift without RPT station

### ISSUE THREAD

**Issue by SP1CIN** [rogerclarkmelbourne/OpenGD77CPS#56]
Good day. I noticed such a problem in this cool software that it is not possible to set the radio to transmit in digital mode when it is set to shift. There is such an option in the radioddity software. Here, unfortunately, you can only transmit in direct mode. It would be nice to add such an option, at least to be able to transmit in shift mode, for example:
TX 145.500- RX 433.500 Cross-band Repeater
. The signal goes through some radios and it's nice if it was possible to force broadcasting not only in direct mode or a normal repeater. best regards

**Comment by rogerclarkmelbourne** [comment]
How is this option enabled in the official CPS.

What repeater operates DMR cross-band, can you send me a link to the details of the repeater.

The firmware does not support Dual Capacity Direct, and is not likely to do so, in the foreseeable future.
