### ISSUE TITLE
Since the last update my RD-5r is power cycling on it own all the time. It will be sitting in monitor or scanning and it will reset 5-6 times in two hours ish? I can’t seem to find an exact pattern. It seems to be random.i put this in the wrong spot again. ugh. sorry 

### ISSUE THREAD

**Issue by VA3NDP** [rogerclarkmelbourne/OpenGD77CPS#58]

**Comment by rogerclarkmelbourne** [comment]
Wrong repo.

I presume you have now reposted this to the firmware repo issues

Try changing Eco to Level 0

**Comment by VA3NDP** [comment]
I will pop it into the right repo when I get back home. I don't seem to have it on my cell. I changed the eco to 0 and it's still doing it. It was doing it since the build just before this one. I thought updating to this one may have helped but no luck. Three builds ago I had no issues with power cycling at all. I will update the proper repo tonight (or tomorrow for you ) 😉

**Comment by rogerclarkmelbourne** [comment]
OK.

Yep. Raise an issue if its still doing it at Eco level 0.

Give as much information as possible, including whether you are using voice prompts etc.
